const blogs = [
    {
        id: '1',
        title: 'Building a Modern Uber Clone with Real-time Tracking',
        screens: 'images/blog/resized_image_1.jpg',
        description: 'A comprehensive guide on developing a ride-sharing application with real-time location tracking and payment integration.',
        author: 'Ayush Kumar',
        authorTitle: 'Software Developer Engineer- 1',
        create_at: '29 Dec, 2024',
        blogSingleImg: 'images/blog/uber-clone-detail.jpg',
        comment: '4',
        blClass: 'format-standard-image',
    },
    {
        id: '2',
        title: 'Creating an AI-Powered Chat Application with Gemini AI',
        screens: 'images/blog/Screenshot 2024-12-29 134056.png',
        description: 'Implementation of a sophisticated chat application leveraging Gemini AI for intelligent conversations and natural language processing.',
        author: 'Ayush Kumar',
        authorTitle: 'AI Developer',
        create_at: '28 Oct, 2024',
        blogSingleImg: 'images/blog-details/chat-app-detail.jpg',
        comment: '4',
        blClass: 'format-standard-image',
    },
    {
        id: '3',
        title: 'Developing a SaaS Platform with OpenAI Integration',
        screens: 'images/blog/openai-content-generation-wordpress-app-as-saas-609860.png',
        description: 'Building a scalable SaaS application with OpenAI APIs for advanced AI capabilities and user-friendly features.',
        author: 'Ayush Kumar',
        authorTitle: 'Software Engineer',
        create_at: '27 Sept, 2024',
        blogSingleImg: 'images/blog-details/saas-detail.jpg',
        comment: '4',
        blClass: 'format-video',
    },
    {
        id: '4',
        title: 'Flipkart Clone: E-commerce Platform Development',
        screens: 'images/blog/153995268-0cb769b9-e0ee-48ea-83c1-09b881df4101.png',
        description: 'A detailed walkthrough of creating a feature-rich e-commerce platform inspired by Flipkart with modern technologies.',
        author: 'Ayush Kumar',
        authorTitle: 'Software Developer Engineer-1',
        create_at: '26 June, 2024',
        blogSingleImg: 'images/blog-details/flipkart-detail.jpg',
        comment: '4',
        blClass: 'format-standard-image',
    },
];

export default blogs;